import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient} from "@tanstack/react-query";
import { WagmiProvider } from "@/services/WagmiProvider";
import { Navbar } from "@/components/common/Navbar";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trade Bot",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <WagmiProvider>
          <BackgroundBeamsWithCollision>
            <Navbar/>
            {children}
          </BackgroundBeamsWithCollision>
        </WagmiProvider>
      </body>
    </html>
  );
}
